#!/usr/bin/env node

/**
 * Generate env.ts file from environment variables
 * This script reads from .env file or process.env and generates a TypeScript file
 * that can be imported at runtime, avoiding issues with .env file loading in packaged apps.
 */

const fs = require("fs");
const path = require("path");
const dotenv = require("dotenv");

// Load .env file if exists
const envPath = path.join(__dirname, "../.env");
if (fs.existsSync(envPath)) {
  console.log("📄 Loading .env file from:", envPath);
  dotenv.config({ path: envPath });
} else {
  console.log("⚠️ No .env file found, using process.env");
}

// Environment variables to include
const ENV_VARS = [
  "VITE_API_URL",
  "VITE_WEBSITE_DOMAIN",
  "VITE_INVITE_WEBSITE_DOMAIN",
  "VITE_SCREENSHOT_INTERVAL",
  "VITE_SYNC_INTERVAL",
  "VITE_PRESENCE_HEARTBEAT_INTERVAL",
];

// Default values for each variable
const DEFAULTS = {
  VITE_API_URL: "",
  VITE_WEBSITE_DOMAIN: "",
  VITE_INVITE_WEBSITE_DOMAIN: "",
  VITE_SCREENSHOT_INTERVAL: "300000", // 5 minutes
  VITE_SYNC_INTERVAL: "60000", // 1 minute
  VITE_PRESENCE_HEARTBEAT_INTERVAL: "15000", // 15 seconds
};

// Generate the env.ts content
function generateEnvFile() {
  const lines = [
    "/**",
    " * Auto-generated environment configuration",
    ` * Generated at: ${new Date().toISOString()}`,
    " * DO NOT EDIT THIS FILE MANUALLY",
    " */",
    "",
    "export const ENV = {",
  ];

  const missingVars = [];

  ENV_VARS.forEach((varName) => {
    const value = process.env[varName] || DEFAULTS[varName];

    if (!value && !DEFAULTS[varName]) {
      missingVars.push(varName);
    }

    // Escape special characters in string
    const escapedValue = value
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n");

    lines.push(`  ${varName}: "${escapedValue}",`);
  });

  lines.push("} as const;");
  lines.push("");
  lines.push("export type EnvKey = keyof typeof ENV;");
  lines.push("");

  // Log warnings for missing variables
  if (missingVars.length > 0) {
    console.warn(
      "⚠️ Warning: The following environment variables are not set:",
    );
    missingVars.forEach((v) => console.warn(`   - ${v}`));
  }

  return lines.join("\n");
}

// Write the file
function main() {
  console.log("🔧 Generating env.ts...");

  const content = generateEnvFile();
  const outputPath = path.join(__dirname, "../src/main/env.ts");

  // Ensure directory exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, content, "utf-8");

  console.log("✅ Generated:", outputPath);

  // Print summary (masked values)
  console.log("\n📋 Environment variables:");
  ENV_VARS.forEach((varName) => {
    const value = process.env[varName] || DEFAULTS[varName];
    const masked = value ? `${value.substring(0, 10)}...` : "(empty)";
    console.log(`   ${varName}: ${masked}`);
  });

  console.log("\n✨ Done!");
}

main();
